### ISSUE TITLE
Agregar la hora y minuto en la fecha en la que se completa una factura

### ISSUE THREAD

**Issue by NicoleBP02** [jdrodas/ServiciosPublicosNoSQL#3]

**Comment by jdrodas** [comment]
Se ha implementado la fecha de cobro de la factura en commit https://github.com/jdrodas/ServiciosPublicosNoSQL/commit/497e7c5599e781eb3e0aa3a901ee730a487067d2, sin embargo la idea es almacenar este dato en la base de datos como fecha y no como string.
